# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eefb98607efd99b969a2bed06c5c24c1bf4c046be57a6495842dea181f9be0ef15c619da923701ca47e7e17430d520828fdd2ede1c67709750613a920ab4ac6

test:
  secret_key_base: adece98afbb0595b388bc01ebda9002474259313d321ec6029588132af72d8a44403becdde1d85cb75b366f03e9ed586e88600d4daa9c01e97d6b07fb438cb93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
